[build]
	command = "yarn build"
	publish = "build"

[[redirects]]
from = '/category/terms-of-service'
to = '/terms'

[[redirects]]
from = '/category/privacy'
to = '/privacy'


[[redirects]]
from = '/terms/vsa'
to = '/terms/service'